//
// Copyright (c) 2008-2011, Kenneth Bell
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

using System;
using System.Collections.Generic;

namespace DiscUtils.Diagnostics;

/// <summary>
/// The report generated by replaying file system actions from a checkpoint.
/// </summary>
/// <remarks>This report contains detailed tracing information.</remarks>
public sealed class ReplayReport
{
    private List<StreamTraceRecord> _globalTraceReport;
    private List<StreamTraceRecord> _traceReport;

    internal ReplayReport(
        Exception failureEx,
        Exception replayEx,
        TracingStream globalTraceStream,
        TracingStream traceStream,
        int replayBufferSize,
        int eventsReplayed,
        long eventsBeforeLockdown,
        string replayPreVerificationReport,
        bool failedVerifyOnReplay,
        string replayVerificationReport,
        string lastCheckpointReport)
    {
        VerificationFailureException = failureEx;
        ReplayException = replayEx;
        _globalTraceReport = [.. globalTraceStream.Log];
        _traceReport = [.. traceStream.Log];
        ReplayEventsAvailable = replayBufferSize;
        ReplayEventsProcessed = eventsReplayed;
        TotalEventsProcessed = eventsBeforeLockdown;
        ReplayPreVerificationReport = replayPreVerificationReport;
        ReplayFailedVerification = failedVerifyOnReplay;
        ReplayVerificationReport = replayVerificationReport;
        LastCheckpointReport = lastCheckpointReport;
    }

    /// <summary>
    /// The exception (if any) that caused the file system verification check to fail.
    /// </summary>
    public Exception VerificationFailureException { get; }

    /// <summary>
    /// The exception (if any) that cause the full replay to fail.
    /// </summary>
    public Exception ReplayException { get; }

    /// <summary>
    /// The stream activities traced whilst replaying the file system action that broke the file system.
    /// </summary>
    public IEnumerable<StreamTraceRecord> InterCheckpointStreamTraceLog => _globalTraceReport;

    /// <summary>
    /// The stream activities traced whilst replaying the file system action that broke the file system.
    /// </summary>
    public IEnumerable<StreamTraceRecord> ReplayStreamTraceLog => _traceReport;

    /// <summary>
    /// The number of replay events available to replay.
    /// </summary>
    public int ReplayEventsAvailable { get; }

    /// <summary>
    /// The number of replay events successfully replayed.
    /// </summary>
    public int ReplayEventsProcessed { get; }

    /// <summary>
    /// Gets whether file system corruption was detected whilst replaying events.
    /// </summary>
    public bool ReplayFailedVerification { get; }

    /// <summary>
    /// Gets the file system verification report generated at the last checkpoint.
    /// </summary>
    public string LastCheckpointReport { get; }

    /// <summary>
    /// Gets the file system verification report generated whilst just before replaying the file system action that failed.
    /// </summary>
    public string ReplayPreVerificationReport { get; }

    /// <summary>
    /// Gets the file system verification report generated whilst replaying the file system action that failed.
    /// </summary>
    public string ReplayVerificationReport { get; }

    /// <summary>
    /// The total number of events processed (ignoring events run during replay).
    /// </summary>
    public long TotalEventsProcessed { get; }
}
