<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Mounts DiscUtils IFileSystem implementations using Dokan file system driver</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DokanNet" Version="2.3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Library\DiscUtils.Core\DiscUtils.Core.csproj" />
    <ProjectReference Include="..\..\Library\DiscUtils.Streams\DiscUtils.Streams.csproj" />
    <ProjectReference Include="..\..\Library\DiscUtils.VirtualFileSystem\DiscUtils.VirtualFileSystem.csproj" />
  </ItemGroup>

</Project>
